version: '3'

services:
  postgres:
    image: postgres
    env_file:
      - .env
    environment:
      POSTGRES_DB: gavel
    volumes:
      - postgres-data:/var/lib/postgresql/data
    command: ["postgres", "-c", "max_connections=200"]

  redis:
    image: redis
    ports:
      - "6379:6379"

  gavel:
    build:
      context: .
    ports:
      - "80:80"
    env_file:
      - .env
    environment:
      PORT: 80
    depends_on:
      - postgres
      - redis
    command: sh -c "python initialize.py && celery -A gavel:celery worker --loglevel=info -E & gunicorn -b :80 -w 3 gavel:app"

volumes:
  postgres-data:
